### PR TITLE
Upgrade to Sentry 8.0

### PR DESCRIPTION
**Pull request by slafs**
Please test and comment

### CODE REVIEW

**Comment by onlydole** [comment]
:+1: This works well for me! I do not have any issues!

**Comment by skeetio** [comment]
No issues here.

**Comment by andrew-dixon** [comment]
@slafs how do I upgrade to a specific branch to test this? Normally to update I do:

```
docker stop sentry
docker rm sentry
docker pull slafs/sentry
docker run...
```

and that gets the latest version. Thanks.

**Comment by slafs** [comment]
hey @andrew-dixon, you need to build your own image from this branch with something like this:
```
git clone https://github.com/slafs/sentry-docker.git
cd sentry-docker
git checkout next/sentry-8.0
docker build -t my_sentry_8_image .
docker run ... my_sentry_8_image ...
```

**Comment by andrew-dixon** [comment]
@slafs Thanks that worked perfectly. Excellent work.

**Comment by andrew-dixon** [comment]
@slafs Since updating earlier today I've had the message "Background workers haven't checked in recently" appear in red across the top of the page a couple of times and looking at the celery worker docker log I'm seeing the following error message over and over:

```
body: '\x80\x02}q\x01(U\x07expiresq\x02U 2016-01-30T17:03:14.899494+00:00q\x03U\x03utcq\x04\x88U\x04argsq\x05]q\x06U\x05chordq\x07NU\tcallbacksq\x08NU\x08errbacksq\tNU\x07tasksetq\nNU\x02idq\x0bU$399fb648-1acd-4cf3-b12a-3508921e12a8q\x0cU\x07retriesq\rK\x00U\x04taskq\x0eU+sentry.tasks.process_buffer.process_pendingq\x0fU\ttimelimitq\x10NN\x86U\x03etaq\x11NU\x06kwargsq\x12}q\x13u.' (274b)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 592, in _receive_callback
    decoded = None if on_m else message.decode()
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 142, in decode
    self.content_encoding, accept=self.accept)
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 174, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```

When I updated I stopped and removed the celery worker before starting Sentry and then the celery worker, so it has been updated as well. Any ideas? Is this an issue with the update?

**Comment by andrew-dixon** [comment]
After a bit of messing around the only way I could get sentry to accept error reports again was to remove the celery options from the environment file, stop and remove sentry and sentry celery worker and then start only sentry again. I still have the "Background workers haven't checked in recently" message but it is receiving error reports again.

**Comment by onlydole** [comment]
@slafs Any news on when this will be live?

**Comment by slafs** [comment]
Yeah, sorry. I was trying to workaround that extra configuration step and I think I figured this out. I'm pretty short on time recently. I'll try to push some updates this week and maybe "release" it next week.

**Comment by onlydole** [comment]
:+1: Excellent! I'm happy to help if needed at all too!

**Comment by andrew-dixon** [comment]
@slafs is that related to the issues I've been seeing, detailed above?

**Comment by slafs** [comment]
@andrew-dixon no sorry, haven't tried to reproduce that. @onlydole can you?

**Comment by onlydole** [comment]
@slafs - Absolutely!

**Comment by onlydole** [comment]
@andrew-dixon, I'm not seeing those issues, it might be an issue with your configuration file, or that you need a reds instance set up additionally.

screen shot 2016-02-08 at 2 23 58 pm

**Comment by onlydole** [comment]
I use a `docker-compose.yml` file and `environment` file to test locally and to orchestrate my instances elsewhere...I'd recommend trying that as an easier way to go about testing.

_For example:_

```
server:
  image: SELF/sentry
  volumes:
    - /tmp/sentry:/data
  ports:
    - "9000:9000"
  env_file:
    - ./environment
  links:
    - redis
    - db
db:
  image: postgres:latest
redis:
  image: redis:latest
sentry_celery_worker:
  image: SELF/sentry
  command: celery worker -B
  volumes:
    - /tmp/sentry:/data
  env_file:
    - ./environment
  links:
    - redis
    - db

```

**Comment by onlydole** [comment]
@slafs - You should be good to push a release!

**Comment by slafs** [comment]
Right, one last thing with this extra configuration step. I think it should be "fixed" now. Please try it out.

**Comment by onlydole** [comment]
Works for me!

**Comment by dz0ny** [comment]
I can confirm successful migration from sentry7 to sentry 8.1.2

and my docker-compose:
```
web:
  container_name: "sentry"
  image: sentry_8
  labels:
    - "traefik.frontend.passHostHeader=true"
  env_file: .env
  restart: always
  links:
   - db
   - redis
  ports:
   - "9000"
worker:
  image: sentry_8
  labels:
    - "traefik.enable=false"
  env_file: .env
  restart: always
  links:
   - db
   - redis
  command: "celery worker -B"
  log_driver: "none"
db:
  image: postgres:9.3
  labels:
    - "traefik.enable=false"
  restart: always
  environment:
    - POSTGRESQL_DB=postgres
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASS=**********************************************
  volumes:
    - /srv/sentry7_db/:/var/lib/postgresql/data/:rw
  log_driver: "none"
redis:
  labels:
    - "traefik.enable=false"
  image: redis:latest
  restart: always
  log_driver: "none"
  volumes:
    - /srv/sentry7_redis/:/data/:rw
```

**Comment by mlegenhausen** [comment]
Works as expected. Updated from 7.4.3 to 8.1.2.

**Comment by onlydole** [comment]
@slafs - will you have a release ready for this week?

**Comment by mlegenhausen** [comment]
Can you also upgrade to Sentry 8.1.2?

**Comment by adamlc** [comment]
Can updates on this? :tada:

**Comment by mlegenhausen** [comment]
Tried out Sentry 8.2.1 without problems. I am now running with this image since two weeks without any problems.

What is annoying is that I can't find a list of all teams to switch in a faster way between them.

**Comment by slafs** [comment]
I, finally, managed to push this to `master`. Check out https://hub.docker.com/r/slafs/sentry/tags/. Thanks everyone for your help.

For Sentry `8.1.2` see https://github.com/slafs/sentry-docker/pull/54. Hopefully that PR won't take that long to merge as this one.

**Pull request merged**
