### PR TITLE
Add support for posixGroup LDAP group type.

### PR DESCRIPTION
**Pull request by grundleborg**
This addresses bug #23 .

### CODE REVIEW

**Comment by slafs** [comment]
great! please also update the description about ``LDAP_GROUP_TYPE`` in README

**Comment by grundleborg** [comment]
Is there anything else needed for this patch to be mergeable?

**Comment by slafs** [comment]
No, sorry for the delay. I will try to merge, hopefully, in this week.

**Comment by slafs** [comment]
Thanks for the PR!

**Pull request merged**
